# Generated by Django 5.0.2 on 2024-07-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=150)),
                ('cr', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
